### ISSUE TITLE
Enhancement - Install and de-install process

### ISSUE THREAD

**Issue by Franck-75** [bbmaster123/10SM#11]
Hi,
I'm not a Windows developer, so I was unable to install your stuff. It's promising.
Can you provide an install - uninstall system for your software ?
Thank you.

**Comment by bbmaster123** [comment]
Hi,
I'm not a windows developer either ;) 

I intend to get to that eventually, once I have some free time to work on the project again. In the middle of some big irl stuff right now that will take a while to get through, but once that's out of the way, absolutely. 

there are also several forks of this project, any of them are welcome and may possibly come up with their own installer in the meantime. Its literally just replacing files, can't be that hard. I just don't want to put out something unreliable in a rush and be responsible for ruining someone's day, ya know?

**Comment by Franck-75** [comment]
Hello,
I understand your concern and you mentionned it in your github. So I'm not surprised.
I was unable to copy the files, this is the reason why I asked for an installer. I don't know the "trick" to do it.
I'm interested about the fork you mentioned but I don't know them.
It could be interresting to mention them...

**Comment by bbmaster123** [comment]
the trick is that you have to take ownership of the original files (so you have full permissions), and start menu can't be running when you replace them. That is essentially what an installer for this would do too, just automated. 

If you look on the main page (for any github repository) on the right hand side near the top you'll see a link to any forks if there are any. If you click that, it will take you to a list of all existing forks. 

Right now, none of the 10SM forks have added anything new, but one of them could potentially push their own update at any time. If not, well like I said, an installer is on the to-do down the line. If you really really can't wait though, I would recommend learning how to replace system files, and them maybe practice in a virtual machine in case you mess up at first.

cheers :)

**Comment by austinjklim** [comment]
would i need to end "startmenuexperiencehost" and "explorer.exe" to replace the files? It seems that ending startmenuexperiencehost, another instance would immediately open after that. I'm having issues replacing some of the files e.g., system32 files in which it says another file or folder was in used.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/bbmaster123/10SM/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted+sort%3Aupdated-desc

@bbmaster123, why is this closed? I haven't been able to locate an installer.

**Comment by SeriesXM** [comment]
> > https://github.com/bbmaster123/10SM/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted+sort%3Aupdated-desc
> 
> @bbmaster123, why is this closed? I haven't been able to locate an installer.

The main page (the ReadMe) has a recommendation for a different program, along with a very detailed explanation why this project is now considered closed.

**Comment by RokeJulianLockhart** [comment]
Perhaps close it as unplanned, then.

**Comment by SeriesXM** [comment]
> Perhaps close it as unplanned, then.

I don't know... I'm not part of this project and never had a chance to try it myself. I had this saved for when I'm forced to use Windows 11, so I just got your notification and thought I'd point you to the main page.
