### ISSUE TITLE
(not an issue, more of a "DM" I just didn't know where to say it) Update ETA (And my personal intentions for this project)

### ISSUE THREAD

**Issue by SamuraisEpic** [bbmaster123/10SM#14]
Hey, this isn't an issue, but there's no discussion tab, so I'm posting here: When can I expect an update? I've wanted to make a custom Gaming-Centric and Functional Windows mod that makes use of 10SM (Because 10's Start Menu and NC are MUCH better [and more functional] than 11's touch-centric ones [kinda like W8 but I digress]) and Rectify11. However, the slow exit bug is kinda painful, and I don't know how to use the Notification Center. I'm not the most "savvy" person around, but I know a thing or 2, and wanted the help of the devs of the Foss projects I plan to use to make this mod possible. I hope this doesn't get you the wrong way because I know you mentioned personal problems, but seeing that Rectify11 V2(.5) came out, I figured I'd get a start. Let me know your plans, hopefully we can "help each other out" (mostly you to me)(lol).

Kind regards, SamuraisEpic.

**Comment by bbmaster123** [comment]
No worries, this is fine, although you can reach me on reddit as well under the same username, bbmaster123

I'm honestly unsure when a significant update will be coming, I have intentions to create an installer and a configuration/settings app to go with it... but I can't give a definite timeline due to both my currently limited time, and how complex the exit bug is. 

I'm not really a developer, so I'm not up to speed using visual studio to create solution files coded in C or whatever, I'm basically just forcing files to work together. Something like explorerpatcher for example is far beyond what I can do. Not that I have given up, I still want to make this available to everyone, hassle-free for free

If you know anyone on the rectify11 team willing to take a look and help, by all means have them go ahead! :)
You and/or the rectify team are welcome to use 10SM in your mods

cheers!

**Comment by SamuraisEpic** [comment]
Hey, thanks for the quick reply. I can't say the same for myself lol. If you've already taken a look through the ExplorerPatcher repo, or the issues tab, then you'd by now know that Valinet has added a potentially experimental fix to the slow close bug to ExplorerPatcher. Now, although this is a great step, and allows potential daily driving of this "tool" on release builds of windows 11, it doesn't work yet for Rectify11 simply because Misha's implementation of ExplorerPatcher is custom, isn't prerelease, and makes it so the official or "original" ExplorerPatcher is severely broken on Rectify11. Now, you can talk to one of the devs of Rectify11 when you have time, and if you want, I can give you Ojas [the main dev]'s email and Discord, and I also provide Misha's Twitter and Discord. You might need to join the RectifyWin Server on Discord to talk to either person there, and if that _is_ the case, I'll provide a link to the server. Again, I don't want to pressure you, no time constraints, and again, I'm just a kid with a love for PCs and the community. I can also help by making a simple installer using a bat/CMD and provide a portable configurator (again using bat/CMD) that can change between Normal Start and Fullscreen Start, and assuming the notification center works with the UseLiteLayout reg, the notification center as well. You could also talk to Valinet about working on the Rectify edition _with Misha_, so that they can work on an exit bug fix together, to provide "full" compatibility on Rectify11, which would be helpful for me. Once again, thanks for the quick reply. 

 

Hope this helps, SamuraisEpic

**Comment by bbmaster123** [comment]
I would still need to read through the new code that fixes the start menu bug, and create a new implementation separate from explorerpatcher with just the code for the start menu. its doable, but I'd also imagine the devs of rectify11 REALLY want this feature for their next release and are probably already starting to test things on their own. 

I just feel like their update will probably be released before I even have a chance to begin.  I'll Check out the fix when I have time regardless, but by that time I don't think there will be much of a point to making a such a short lived, temporary implementation

**Comment by SamuraisEpic** [comment]
Actually, the Rectify11 part, is all me. Sorry. But that should give you more "time". I also heard that their next release is based on a stable Nickel build, so it'll be a while. Meanwhile, valinet mentioned that his fix involved spoofing Start
