### ISSUE TITLE
Windows 10 Notification center

### ISSUE THREAD

**Issue by Lixkote** [bbmaster123/10SM#18]
@bbmaster123 Could you atleast tell us how you managed to enable that non working(or semi working) notification panel from windows 10?

**Comment by bbmaster123** [comment]
I swear I mentioned it somewhere else, but here is a list of the files I can remember replacing. This only works on stable builds, on dev and beta builds clicking the button will do nothing.

C:\windows\systemapps\ShellExperienceHost_cw5n1h2txyewy\shellexperiencehost.exe
C:\windows\systemapps\ShellExperienceHost_cw5n1h2txyewy\shellexperiencehost.exe
C:\windows\systemapps\ShellExperienceHost_cw5n1h2txyewy\shellexperiencehost.exe

**Comment by chuck00000** [comment]
where's the " C:\windows\Windows\SystemResources\actioncenter.dll.mun " file? I can't find in previous uploads

**Comment by HamzehTamimi** [comment]
@bbmaster123 i tired doing this but when clicking action center it does not open

**Comment by HamzehTamimi** [comment]
but i can't find file "C:\windows\SystemResources\actioncenter.dll.mun"
