### ISSUE TITLE
Setting of "Which apps are displayed in the start menu" in the Settings App does not work

### ISSUE THREAD

**Issue by Shomnipotence** [bbmaster123/10SM#4]
This is not a big problem, it seems that the setting of "Which folders are displayed in the start menu" in the Settings App does not work

**Comment by bbmaster123** [comment]
seems to work on my end, but you need to access it through settings first. after that you can right click to get personalize this list.
I tested every toggle and they all work, on build 282 fully updated
do the buttons not show up, or does the start menu crash?
