### ISSUE TITLE
Enabling fullscreen mode

### ISSUE THREAD

**Issue by SheaSmith** [bbmaster123/10SM#6]
I've managed to get the start menu working, but I can't see an option for fullscreen in Settings. How can it be enabled?

**Comment by bbmaster123** [comment]
you need to use group policy editor since there is no user exposed setting for that anymore.

go to user configuration > Administrative Templates > Start Menu and Taskbar and enable Force Start  to be either full screen size or menu size, then sign out and in.

cheers!

**Comment by SheaSmith** [comment]
I'm running Windows 11 Home, so I wasn't able to use Group Policy, so I just used the registry tweak in [this](https://www.thewindowsclub.com/how-to-enable-windows-10-full-screen-start-menu-using-regedit-or-gpedit) article instead, and it's working perfectly.

Thanks.
