### ISSUE TITLE
 Can I use or import magnet content directly from the Windows 10 Start menu?

### ISSUE THREAD

**Issue by huangsijun17** [bbmaster123/10SM#8]
I want to upgrade to win11, but there are many links in the live tile of windows10. Upgrading will cause these settings to be discarded. Can this program import them directly?

**Comment by bbmaster123** [comment]
I'm not 100% sure what you mean, are you asking about the tile layout you setup on windows 10? That data should remain after the upgrade to windows 11, and so when you put the windows 10 start menu back the tile layout will come up as before without you having to do anything else.

If you want to be extra safe, you can also use winaero tweaker to backup the start menu layout to a file, and restore the backup if it doesn't automatically come up on its own. Also IMO, just handy to have just in case.

hope that helps :)
